name: ARVO CI

on:
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:  # keep this for manual runs

jobs:
  arvo-reproducer-ci:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout ARVO
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install -y sudo vim gdb wget git curl python3 tmux ipython3 python3-pip python3.12-venv lsb-release gnupg git-lfs

    - name: Setup /src/ARVO
      run: |
        sudo mkdir /src
        sudo mkdir /data
        sudo cp -a $GITHUB_WORKSPACE /src/ARVO
        sudo chown -R $USER:$USER /src
        sudo chown -R $USER:$USER /data
    - name: Setup Python venv
      run: |
        python3 -m venv /src/arvo_venv
        source /src/arvo_venv/bin/activate
        cd /src/ARVO/
        pip3 install -e .

    - name: Git LFS pull and extract metadata
      run: |
        cd /src/ARVO
        git lfs pull
        cp profile.template arvo/_profile.py
        cd arvo
        tar -xvf oss_fuzz_meta.tar

    - name: Install docker-cli
      run: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
          gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
          https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          | sudo tee /etc/apt/sources.list.d/docker.list
        sudo apt-get update
        sudo apt-get install -y docker-ce-cli

    - name: Run ARVO test
      run: |
        source /src/arvo_venv/bin/activate
        cd /src/ARVO
        rm -f ./Reports/25402.json
        arvo report 25402
        grep "322716256d60e316c9a3b905a387be36d4e47368" ./Reports/25402.json
